<?php

use Carbon\Carbon;
use ThinkReaXMLParser\Objects\Media;

;

class MediaTest extends PHPUnit_Framework_TestCase
{
    protected $stub;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->stub = simplexml_load_file("stubs/objects.xml");
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testMedia()
    {
        $media = new Media($this->stub);

        $this->assertInternalType('array', $media->getImages());
        $this->assertInternalType('array', $media->getFloorplans());
        $this->assertCount(16, $media->getImages());
        $this->assertCount(2, $media->getFloorplans());
        // the first one was the "m" record. Make sure it's 1
        $this->assertSame(1, $media->getImages()[0]->getOrdering());
        $this->assertSame("Rockend_TESTTHINKERY1_20160426125002/00315_01.jpg", $media->getImages()[0]->getFilename());
        $this->assertSame("jpg", $media->getImages()[0]->getFiletype());
        $this->assertInstanceOf(Carbon::class, $media->getImages()[0]->getModified());
        $this->assertSame("2016-04-19 07:36:37", $media->getImages()[0]->getModified()->toDateTimeString());
        // the 14th is the "n" record. Make sure it's 14
        $this->assertSame(14, $media->getImages()[13]->getOrdering());
        $this->assertSame("Rockend_TESTTHINKERY1_20160426125002/00315_14.jpg", $media->getImages()[13]->getFilename());
        // check the floorplans
        $this->assertSame(1, $media->getFloorplans()[0]->getOrdering());
        $this->assertSame("Rockend_TESTTHINKERY1_20160426125002/00315_floorplan.jpg", $media->getFloorplans()[0]->getFilename());
        // check filepath
        $this->assertSame(2, $media->getFloorplans()[1]->getOrdering());
        $this->assertSame("http://fakeurl.com/Rockend_TESTTHINKERY1_20160426125002/00315_10.jpg", $media->getFloorplans()[1]->getUrl());
    }
}