<?php

use ThinkReaXMLParser\Objects\FloorplanObject;
use ThinkReaXMLParser\Objects\ImageObject;
use ThinkReaXMLParser\Objects\Listings\BusinessListing;
use ThinkReaXMLParser\Objects\Listings\RentalListing;

class WithdrawnListingTest extends PHPUnit_Framework_TestCase
{
    protected $xml;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->xml = simplexml_load_file("stubs/withdrawn.xml");
    }
    
    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testWithdrawnListingsParser()
    {
        $parsed = new RentalListing($this->xml);

        $this->assertSame('CR_BOURKE_TEST-515', $parsed->getUniqueId());
        $this->assertSame('withdrawn', $parsed->getStatus());
        $this->assertInstanceOf(\Carbon\Carbon::class, $parsed->getModified());
    }
}
